services:
    # Flask API service
    - type: web
      name: tts-backend
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn server:app
      envVars:
          - key: PYTHON_VERSION
            value: 3.9.0
          # PORT is automatically set by Render, no need to define it

    # Next.js frontend
    - type: web
      name: tts-frontend
      env: node
      buildCommand: npm install && npm run build
      startCommand: npm start
      envVars:
          - key: FLASK_API_URL
            fromService:
                name: tts-backend
                type: web
                property: url
          # This automatically sets FLASK_API_URL to the backend service URL
