import React from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from './utils/ThemeContext';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const Layout = ({ children }) => {
	return (
		<div className='min-h-screen flex flex-col'>
			<header className='bg-blue-600 text-white p-4'>
				<h1 className='text-xl font-bold'>My Website</h1>
			</header>
			<main className='flex-grow'>{children}</main>
			<footer className='bg-gray-800 text-white p-4 text-center'>
				<p>&copy; 2023 My Website. All rights reserved.</p>
			</footer>
		</div>
	);
};

export default function RootLayout({ children }) {
	return (
		<ThemeProvider>
			<html lang='en'>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<Layout>{children}</Layout>
				</body>
			</html>
		</ThemeProvider>
	);
}
